### ISSUE TITLE
Default Activity Couldnt Found

### ISSUE THREAD

**Issue by AndroidFrk** [codeka/advbatterygraph#2]
Hi there, i just downloaded your project and imported as existing project in Android Studio. I'm trying to run it on my nexus 5 but it gives an error while compiling the code. 

This is the error which console shows:
"Could not identify launch activity: Default Activity not found
Error while Launching activity"

I notice that in Android Menifestfile, there is not any default activity defined. I even tried setting the SettingsActivity as default activity but still the app crashes. I'm a bit new to android development so if you could help me figure out this problem, I would really appreciate it!

**Comment by codeka** [comment]
That's right, because it's just a widget, there's no main activity so Android Studio won't know what to launch. You should still be able to add the widget from the "Widgets" menu and go from there, though.
