### ISSUE TITLE
Cannot export to CSV - Zero size file

### ISSUE THREAD

**Issue by puppyscrubber** [codeka/advbatterygraph#3]
Thanks for the app Codeka, It's the best app out there for my phone!!! (It works reliably when others don't, other than this issue, of course ! :-) )

I'm Using it on an Xiaomi with MIUI (Their UI on top of android) and android 7.0

The export feature exports a zero byte CSV file. (I've tried sharing to different types of mail and Whatsapp etc with the some zero length file.)

I cannot get any type of bug or crash report as it seems the app doesn't actually crash, it just cannot put data into the file.

Ill try on another phone and try to look at the phones filesystem to get some clues if possible.

Any ideas to try to fix, perhaps its a file permission thing?

Regards,

Steve

**Comment by codeka** [comment]
Followed up offline, it seems to be working now. I've uploaded a new version to the Play Store which adds additional logging, so if it happens again then fresh logs will surely help.
